In [27]:
import numpy as np


# **Creating Array**

In [28]:
b = [2,3,7]        #1D array (Vector)
a = np.array(b)

print(a)

[2 3 7]


In [29]:
c = np.array([[2,4],[9,5], [8, 7]])      #2D array (Matrix)

print(c)

[[2 4]
 [9 5]
 [8 7]]


# **Array Initialization**

In [6]:
x = np.zeros((8,9))

print(x)


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
y = np.ones((5,6))
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [8]:
v = np.eye((9))
print(v)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [25]:
np.random.seed(42)

rand_mantrix = np.random.rand(4,5)
print(rand_mantrix)





[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]


In [ ]:
np.random.seed(90)

c = np.random.randint(9, size = [4,5])
print(c)



[[2 3 7 4 5]
 [2 0 3 0 2]
 [2 0 0 8 0]
 [4 0 6 0 1]]


In [ ]:
c = np.array([[2,4],[9,5], [8, 7]])

d = c.flatten()

print(c)
print(d)

[[2 4]
 [9 5]
 [8 7]]
[2 4 9 5 8 7]


In [ ]:
c = np.array([[2,4],[9,5], [8, 7]])

print(c)

print(c.shape)

[[2 4]
 [9 5]
 [8 7]]
(3, 2)


In [ ]:
c = np.array([[2,4],[9,5], [8, 7]])

c = np.reshape(c, (2,3))
print(c)

print(c.shape)

[[2 4 9]
 [5 8 7]]
(2, 3)


In [ ]:
g = np.full((4,5), 8)


g = g.reshape(5,4)

print(g)

print(g.shape)



[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
(5, 4)


In [26]:
a = np.array([4,5,8,9])

b = np.array([1,2,3,4])

print(a)
print(b)

print("---------------")
print(a+b)
print(a-b)
print(a*b)
print(a/b)


x = np.dot(a,b)

print(f" X = {x}")



[4 5 8 9]
[1 2 3 4]
---------------
[ 5  7 11 13]
[3 3 5 5]
[ 4 10 24 36]
[4.         2.5        2.66666667 2.25      ]
 X = 74


In [ ]:
c = np.array([[2,4], [9,5], [8, 7]])

d = np.array([[5,6], [2,7], [7,7]])
d = d.reshape(2,3)

print(c)
print(d)

x = np.dot(c,d)

print(x)

y = np.matmul(c,d)

print(y)




[[2 4]
 [9 5]
 [8 7]]
[[5 6 2]
 [7 7 7]]
[[38 40 32]
 [80 89 53]
 [89 97 65]]
[[38 40 32]
 [80 89 53]
 [89 97 65]]


In [ ]:
c = np.array([[2,4], [9,5], [8, 7]])

print(c)

print(c.T)

c = np.transpose(c)

print(c)

[[2 4]
 [9 5]
 [8 7]]
[[2 9 8]
 [4 5 7]]
[[2 9 8]
 [4 5 7]]


In [ ]:
c = np.array([[2,4], [9,5]])

i = np.linalg.inv(c)

print(i)


m = np.matmul(c,i)

print(m)

[[-0.19230769  0.15384615]
 [ 0.34615385 -0.07692308]]
[[ 1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00]]


In [ ]:
det = np.linalg.det(c)

print(det)


-26.000000000000004


In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([
    [2, 3, -1],
    [-1, 7, 2],
    [4, -3, 5]
])

# Constant vector B
B = np.array([5, 3, 2])

# Solve for X
X = np.linalg.solve(A, B)

print("Solution [x, y, z]:", X)


Solution [x, y, z]: [ 1.33561644  0.69178082 -0.25342466]
